class MonitoringAPI:
    cpu_usage_time_url = "kubernetes.io/container/cpu/core_usage_time"
    cpu_request_utilization_url = "kubernetes.io/container/cpu/request_utilization"
    cpu_limit_utilization_url = "kubernetes.io/container/cpu/limit_utilization"
    cpu_utilization_url = "kubernetes.io/container/cpu/utilization"
    cpu_request_cores_url = "kubernetes.io/container/cpu/request_cores"
    cpu_limit_cores_url = "kubernetes.io/container/cpu/limit_cores"
    memory_used_bytes_url = "kubernetes.io/container/memory/used_bytes"
    memory_limit_bytes_url = "kubernetes.io/container/memory/limit_bytes"
    memory_request_bytes_url = "kubernetes.io/container/memory/request_bytes"
    memory_request_utilization_url = "kubernetes.io/container/memory/request_utilization"
    ephemeral_storage_limit_bytes_url = "kubernetes.io/container/ephemeral_storage/limit_bytes"
    ephemeral_storage_request_bytes_url = "kubernetes.io/container/ephemeral_storage/request_bytes"
    ephemeral_storage_used_bytes_url = "kubernetes.io/container/ephemeral_storage/used_bytes"